import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Example from '@/components/Header'
import 'tailwind.config'
import Products from '@/components/Products'
import Footer from '@/components/Footer'
import PromoSection from '@/components/PromoSection'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>AVAZNELI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Example/>
        <PromoSection/>
        <Products/>
        <Footer/>
      </main>
    </>
  )
}
